spring:
  flyway:
    locations: db/migrations
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/electronic_shop_tvo}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:pokus}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_ISSUER_URI}
          audiences:
            - ${AZURE_CLIENT_ID}
            - api://${AZURE_CLIENT_ID}
server:
  port: 1409
  servlet:
    context-path: "/api"